export * from './recognition/controllers'
export * from './albums/controllers'
export * from './search/controllers'
export * from './songs/controllers'
export * from './artists/controllers'
export * from './modules'
export * from './telemetry/controllers/telemetry.controller'
export * from './auth/controllers/auth.controller'
